# Generated by Django 4.0.4 on 2022-05-12 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsmodel',
            name='body_title',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
