# Generated by Django 4.0.4 on 2022-05-12 23:38

import Core.models.partners
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_aboutpagemodel_body_2_aboutpagemodel_title_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('img', models.ImageField(blank=True, null=True, upload_to=Core.models.partners.upload_location)),
            ],
        ),
    ]
