# Generated by Django 4.0.4 on 2022-05-13 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0006_remove_projectsmodel_category_categorymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectsmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='Core.projectcategoriesmodel'),
        ),
        migrations.DeleteModel(
            name='CategoryModel',
        ),
    ]
