# Generated by Django 4.0.4 on 2022-05-13 01:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0007_projectsmodel_category_delete_categorymodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectsmodel',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='Core.projectcategoriesmodel'),
        ),
    ]
