# Generated by Django 4.0.4 on 2022-05-13 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0009_remove_aboutpagemodel_body_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutpagemodel',
            name='body_2',
            field=models.TextField(blank=True, max_length=355, null=True),
        ),
    ]
