# Generated by Django 4.0.4 on 2022-05-14 19:52

import Core.blogs.Partners
import Core.blogs.mainpage
import Core.blogs.service
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0010_aboutpagemodel_body_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeaderServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='title')),
                ('body_one', models.TextField(verbose_name='body_1')),
                ('body_two', models.TextField(verbose_name='body_2')),
                ('body_three', models.TextField(verbose_name='body_3')),
                ('image', models.ImageField(blank=True, null=True, upload_to=Core.blogs.service.upload_location)),
            ],
        ),
        migrations.CreateModel(
            name='ItAboutModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=70, verbose_name='title')),
                ('about', models.CharField(max_length=10000, verbose_name='about')),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='photo')),
                ('video', models.FileField(blank=True, null=True, upload_to='video/%y')),
            ],
        ),
        migrations.CreateModel(
            name='MainPageAboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MainPageBlogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=Core.blogs.mainpage.upload_location)),
                ('image1_title', models.CharField(max_length=50)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=Core.blogs.mainpage.upload_location)),
                ('image2_title', models.CharField(max_length=50)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=Core.blogs.mainpage.upload_location)),
                ('image3_title', models.CharField(max_length=50)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=Core.blogs.mainpage.upload_location)),
                ('image4_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MainPageHeaderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=50)),
                ('image1', models.ImageField(blank=True, null=True, upload_to=Core.blogs.mainpage.upload_location)),
                ('title2', models.CharField(max_length=50)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=Core.blogs.mainpage.upload_location)),
                ('title3', models.CharField(max_length=50)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=Core.blogs.mainpage.upload_location)),
            ],
        ),
        migrations.CreateModel(
            name='MainPageNumbersModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('num1', models.IntegerField()),
                ('title1', models.CharField(max_length=50)),
                ('num2', models.IntegerField()),
                ('title2', models.CharField(max_length=50)),
                ('num3', models.IntegerField()),
                ('title3', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MainPageServiceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('body', models.TextField()),
                ('image1', models.ImageField(blank=True, null=True, upload_to=Core.blogs.mainpage.upload_location)),
                ('image1_title', models.CharField(max_length=50)),
                ('image2', models.ImageField(blank=True, null=True, upload_to=Core.blogs.mainpage.upload_location)),
                ('image2_title', models.CharField(max_length=50)),
                ('image3', models.ImageField(blank=True, null=True, upload_to=Core.blogs.mainpage.upload_location)),
                ('image3_title', models.CharField(max_length=50)),
                ('image4', models.ImageField(blank=True, null=True, upload_to=Core.blogs.mainpage.upload_location)),
                ('image4_title', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MainService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_title', models.CharField(blank=True, max_length=20, null=True, verbose_name='services')),
                ('blog_title', models.CharField(max_length=30, verbose_name='blog_title')),
                ('comment', models.TextField(verbose_name='comment')),
                ('list_body', models.TextField(verbose_name='body')),
                ('page_body', models.TextField(verbose_name='body')),
                ('photo_body', models.TextField(verbose_name='body')),
                ('pages_body', models.TextField(verbose_name='body')),
                ('ios_body', models.TextField(verbose_name='body')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name=Core.blogs.service.upload_location)),
            ],
        ),
        migrations.CreateModel(
            name='PartnersModels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('logo_1', models.ImageField(blank=True, null=True, upload_to=Core.blogs.Partners.upload_location)),
                ('logo_2', models.ImageField(blank=True, null=True, upload_to=Core.blogs.Partners.upload_location)),
                ('logo_3', models.ImageField(blank=True, null=True, upload_to=Core.blogs.Partners.upload_location)),
                ('logo_4', models.ImageField(blank=True, null=True, upload_to=Core.blogs.Partners.upload_location)),
                ('logo_5', models.ImageField(blank=True, null=True, upload_to=Core.blogs.Partners.upload_location)),
                ('logo_6', models.ImageField(blank=True, null=True, upload_to=Core.blogs.Partners.upload_location)),
                ('logo_7', models.ImageField(blank=True, null=True, upload_to=Core.blogs.Partners.upload_location)),
                ('logo_8', models.ImageField(blank=True, null=True, upload_to=Core.blogs.Partners.upload_location)),
                ('logo_9', models.ImageField(blank=True, null=True, upload_to=Core.blogs.Partners.upload_location)),
                ('logo_10', models.ImageField(blank=True, null=True, upload_to=Core.blogs.Partners.upload_location)),
                ('logo_11', models.ImageField(blank=True, null=True, upload_to=Core.blogs.Partners.upload_location)),
                ('logo_12', models.ImageField(blank=True, null=True, upload_to=Core.blogs.Partners.upload_location)),
                ('logo_13', models.ImageField(blank=True, null=True, upload_to=Core.blogs.Partners.upload_location)),
                ('logo_14', models.ImageField(blank=True, null=True, upload_to=Core.blogs.Partners.upload_location)),
                ('logo_15', models.ImageField(blank=True, null=True, upload_to=Core.blogs.Partners.upload_location)),
                ('logo_16', models.ImageField(blank=True, null=True, upload_to=Core.blogs.Partners.upload_location)),
                ('logo_17', models.ImageField(blank=True, null=True, upload_to=Core.blogs.Partners.upload_location)),
                ('logo_18', models.ImageField(blank=True, null=True, upload_to=Core.blogs.Partners.upload_location)),
                ('logo_19', models.ImageField(blank=True, null=True, upload_to=Core.blogs.Partners.upload_location)),
                ('logo_20', models.ImageField(blank=True, null=True, upload_to=Core.blogs.Partners.upload_location)),
            ],
        ),
    ]
